import {ThemeProvider} from "next-themes";
import "./globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body suppressHydrationWarning={true}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header/>
          <main>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
